### ISSUE TITLE
Regional decimal seperator

### ISSUE THREAD

**Issue by Toxaris-NL** [acivux/SvgMath#2]
There is an issue with the decimal seperator. The program assumes the decimal seperator of Windows is a period, but over here the decimal seperator is a comma. The program will create an SVG, but it cannot be opened as all the values are wrong.

**Comment by Toxaris-NL** [comment]
What seems to work, is adding the following code:

System.Globalization.CultureInfo customCulture = (System.Globalization.CultureInfo)System.Threading.Thread.CurrentThread.CurrentCulture.Clone();
customCulture.NumberFormat.NumberDecimalSeparator = ".";
System.Threading.Thread.CurrentThread.CurrentCulture = customCulture;

**Comment by acivux** [comment]
Are you talking about the actual seperators inside the SVG file? Example:
`<svg:g transform="translate(0, 2.70099609375)">`
should be
`<svg:g transform="translate(0, 2,70099609375)">`

**Comment by Toxaris-NL** [comment]
No, it is vice vera. I see the comma instead of the period. The comma is the decimal seperator, so during all the calculations the values are interpretated wrong causing the resulting value totally wrong. Not just a factor 1000, but totally different values.
If I set the decimal seperator to a period, it all works. The other option is to use CultureInfo.InvariantCulture for the calculations. That would ignore any local setting. However, I suspect that would be a lot of changes in the code to do it for all calculations...

**Comment by acivux** [comment]
Now generating number strings with the invariant culture with this [commit](https://github.com/acivux/SvgMath/commit/5366985ea168556d01db66b013d9e19d7376537e)

**Comment by Toxaris-NL** [comment]
Thanks!
